apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: ProviderConfig
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  projectID: crossplaneprojects
  credentials:
    source: Secret
    secretRef:
      namespace: upbound-system
      name: gcp-secret
      key: creds