apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: providerconfig
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  projectID: devops-425305
  credentials:
    source: Secret
    secretRef:
      namespace: upbound-system
      name: gcp-secret
      key: creds