apiVersion: compositions.io/v1alpha1
kind: XCluster
metadata:
  name: ${{ values.clusterName }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  parameters:
    clusterName: ${{ values.clusterName }}
    region: ${{ values.region }}
    machineType: ${{ values.machineType }}
    nodeCount: ${{ values.nodeCount }}
    repo: "{{ index (splitList '=' (index (splitList '&' (splitList '?' .values.repoUrl).1) 1)) 1 }}"
    owner: "{{ index (splitList '=' (index (splitList '&' (splitList '?' .values.repoUrl).1) 0)) 1 }}"
  compositionRef:
    name: gke-cluster-nodepool